### PR TITLE
fix: not authorized issue by making handleMessage public

### PR DESCRIPTION
**Pull request by gcranju**
### Commit Message

```bash
fix: not authorized issue by making handleMessage public
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [x] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by AntonAndell — APPROVED** [review]
LGTM

**Comment by izyak** [comment]
handleBTPError should be fixed as well. Only handleBTPMessage is fixed.

**Review by izyak — CHANGES_REQUESTED** [review]
fix for handleBTPError as well

**Review by izyak — APPROVED** [review]

**Review by AntonAndell — APPROVED** [review]
LGTM

**Pull request merged**
