### PR TITLE
docs: add xcall-multi contract address for respective chain

### PR DESCRIPTION
**Pull request by DeepakBomjan**
* add relayer path configuration

### Commit Message

```bash
type: commit message
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [x] I only have one commit (if not, squash them into one commit).
- [x] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by AntonAndell** [comment]
What i would like also is connection addresses and network id. So we can see what xCalls there are and what connections and what routes that are available

**Comment by DeepakBomjan** [comment]
> What i would like also is connection addresses and network id. So we can see what xCalls there are and what connections and what routes that are available

Added.

**Comment by AntonAndell** [comment]
@DeepakBomjan  
Could you merge and add this PR into this? 
https://github.com/icon-project/xcall-multi/pull/153

**Comment by DeepakBomjan** [comment]
> @DeepakBomjan Could you merge and add this PR into this? #153

#153 has been already merged.

**Review by ibrizsabin — APPROVED** [review]

**Pull request merged**
